server:
  port: 9909


spring:
  datasource:
    url: jdbc:mysql://cdb-dzs2o6lc.cd.tencentcdb.com:10018/pinyougoudb
    username: root
    password: liu20000406
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1215855088@qq.com #QQ邮箱
    password: htwqtglfzbjejhdg #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致
  redis:
    host: 127.0.0.1
    password:
    timeout: 8000
    port: 6379
    database: 0