swagger:
  enabled: true

server:
  port: 8086

spring:
  application:
    name: lg-seckill-controller
##CAS服务地址
cas:
  server:
    host:
      #CAS服务登录地址
      url: http://localhost:8080/cas
      #CAS服务登出地址
      login_url: ${cas.server.host.url}/login
      #应用访问地址
      logout_url: ${cas.server.host.url}/logout?service=http://localhost/front/index.html

app:
  server:
    host:
      url: http://localhost:8086
  #应用登录地址
  login:
    url: /login
  #应用登出地址
  logout:
    url: /logout

dubbo:
  registry:
    #address: nacos://47.105.207.20:8848
    address: nacos://127.0.0.1:8848
  # 提供者需要配置扫描接口
  # scan:
  # base-packages: com.mxc.web.impl
  protocol:
    port: 20884
  # 消费者默认不检测是否有服务注册
  consumer:
    check: false
    timeout: 10000
# nacos配置中心
#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
#    # 命名空间的id
#    namespace: 7d32a129-a6ca-4ba1-a75e-96aaed89da33