server:
  port: 8001

dubbo:
  scan:
    base-packages: com.lg.product.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848

project:
  leader:
    email: 1013629501@qq.com


spring:
  servlet:
    multipart:
      max-file-size: 888888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #    支持发布确认
    publisher-confirms: true
    #    支持发布返回
    publisher-returns: true
    listener:
      simple:
        #      采用手动应答
        acknowledge-mode: manual
        #        当前监听容器数
        concurrency: 1
        #        最大数
        max-concurrency: 1
        #        是否支持重试
        retry:
          enabled: false
  application:
    name: lg-product-service
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://cdb-dzs2o6lc.cd.tencentcdb.com:10018/pinyougoudb
    username: root
    password: liu20000406
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  output:
    ansi:
      enabled: detect

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lg.product.model.domain
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: ignored
      #驼峰下划线转换
      column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #--------七牛配置
qiniu:
  access:
    key: syZMJO8mXCWFCVaDJ_3WEeeWed5o_eU3drZfE49x
  secret:
    key: 5PTalH1Y70jfPIjQXXKCkQn-QQl6Qc4cRQckOwRy
  bucket:
    name: image
    host:
      name: po4w4fx60.bkt.clouddn.com
